all: encrypt decrypt smartoutput
	cobc -x -free -Wall -O a3.cob
encrypt:
	cobc -m -free -Wall -O encrypt.cob
decrypt:
	cobc -m -free -Wall -O decrypt.cob
smartoutput:
	cobc -m -free -Wall -O smartoutput.cob
